apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  # Use cert-manager to create TLS secrets named `tls-wanderblog` for your host
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wanderblog.online
      secretName: tls-wanderblog
  rules:
    - host: wanderblog.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
